version: '2'
services:
  website:
    build: php-with-apm
    depends_on:
      - mysql
    volumes:
      - ./php-apm.ini:/usr/local/etc/php/conf.d/php-apm.ini
      - ./website:/var/www/html
    ports:
      - 8000:80
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apm
      MYSQL_USER: apm
      MYSQL_PASSWORD: apms3cr3t
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - 3306:3306
